### ISSUE TITLE
Review code from 25ID

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/tiled-viz2023#1]
Examine the code implemented by @canismarko for APS 25ID.  Is this a good starting point?

**Comment by rodolakis** [comment]
https://github.com/spc-group/haven/blob/main/firefly/run_browser.py

**Comment by rodolakis** [comment]
<img width="693" alt="image" src="https://github.com/BCDA-APS/tiled-viz2023/assets/39918069/d603f3c4-d13a-46cc-a9df-600e6b49e0a1">

**Comment by canismarko** [comment]
Things that I can think of off the top of my head that would need to be modified:

1. Create a new ``QApplication`` and ``QMainWindow`` since the ones I used have a lot of signals/slots that are specific to our beamline.
2. Remove the technique specific filters (e.g. "Edge")
3. Remove tabs for "XRF" and other beamline specific details.
4. [Optional] Make this customizable so that I could put #1-3 back in for our application.
